P0 (DEFINE 40 MORE VARIABLES WITH COMMAND "DEFM 40")

1 VAC
2 PRINT "CROSS TOTAL":INPUT "X-ITEM NO. ",A:IF A>58 THEN 2
3 B=B+1
4 FOR D=1 TO A
5 PRINT "Y";B;"-X";D;:INPUT E
6 C=C+E:F=F+E:G(D)=G(D)+E
6 NEXT D
8 PRINT "Y";B;"=";C:C=0:GOTO 3

P1

1 FOR D=1 TO A
2 G=RND(G(D)/F,-3)*100
3 PRINT "X(";D;")=",G(D);"(";G;"%)"
4 NEXT D
5 PRINT "GRAND T.=";F:GOTO 1
